let a = 15;
let b = -5;
let c = 10;
let d = 20;
let ternary = a > b ? a : b;
console.log(ternary);
let ternary1 = a > b ? b : a;
console.log(ternary1);
console.log(50);
console.log(0.5);
console.log(5);
let greaterthan = b > a;
console.log(greaterthan);
let lessthan = b < a;
console.log(lessthan);
let notoperator = a !== b;
console.log(notoperator);
let equaloperator = a === b;
console.log(equaloperator);
let andoperator = a > b && c < d;
console.log(andoperator);
let oroperator = c > d || b < a;
console.log(oroperator);
let andoperator1 = a < b && c < d;
console.log(andoperator1);
let oroperator1 = c > d || b > a;
console.log(oroperator1);
let isAlpha = true;
console.log(isAlpha);

let isAlpha1 = false;
console.log(isAlpha1);
let e = 123;
let f = 456;
console.log(e, f);
let g = 128;
console.log(g);
let ternary3 = g > f ? g : f;
console.log(ternary3);
let ternary2 = e > g ? e : g;
console.log(ternary2);

let str1 = "world";
let str2 = "World";
let ternary4 = str1 > str2 ? str1 : str2;
console.log(ternary4);
